name: ci

on:
  push:
    paths:
      - "**.c"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true



jobs:

  unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
    - &checkout
       uses: actions/checkout@v6

    - run: cmake --workflow default


  int64:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - *checkout

    - run: cmake --workflow int64


  windows_mingw:
    runs-on: windows-latest
    timeout-minutes: 5

    env:
      CMAKE_GENERATOR: Ninja


    steps:
    - *checkout

    - run: cmake --workflow default
